### ISSUE TITLE
有崩溃

### ISSUE THREAD

**Issue by chunfengyao** [rRemix/APlayer#150]
java.lang.NullPointerException: cover_container must not be null
	at remix.myplayer.ui.fragment.player.a$a.c(RoundCoverFragment.kt:1)
	at c.b.a.e.b(Spring.java:31)
	at c.b.a.b.b(BaseSpringSystem.java:3)
	at c.b.a.b.f(BaseSpringSystem.java:3)
	at c.b.a.a$a$a.doFrame(AndroidSpringLooperFactory.java:3)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1079)
	at android.view.Choreographer.doCallbacks(Choreographer.java:901)
	at android.view.Choreographer.doFrame(Choreographer.java:826)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1066)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8086)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by rRemix** [comment]
必现吗？还是随机

**Comment by chunfengyao** [comment]
偶现，但频率有点高。
