### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by Nachogao** [rRemix/APlayer#239]
无法正常开启，开启即崩溃

![crash-remix-myplayer-24_03-12-50-39_381.zip](https://github.com/rRemix/APlayer/files/14735983/crash-remix-myplayer-24_03-12-50-39_381.zip)

**Comment by Nachogao** [comment]
忘了把机型放上
Oppo Reno 10
ColorOs 13.1 (Android 13)

**Comment by rRemix** [comment]
软件版本是多少

**Comment by Nachogao** [comment]
> 软件版本是多少

1.6.2.0
最新版

**Comment by rRemix** [comment]
试试这个版本

https://www.lanzouw.com/i2X5u1sh2cyf
密码:eny5

**Comment by Nachogao** [comment]
> 试试这个版本
> 
> https://www.lanzouw.com/i2X5u1sh2cyf
> 密码:eny5

还是不行

`FATAL EXCEPTION: ModernAsyncTask #2
Process: remix.myplayer, PID: 7675
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$c.done(SourceFile:38)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: getString(...) must not be null
	at remix.myplayer.util.l.g(SourceFile:99)
	at remix.myplayer.ui.fragment.GenreFragment$a.F(SourceFile:3)
	at remix.myplayer.ui.fragment.GenreFragment$a.C(SourceFile:1)
	at androidx.loader.content.a.E(SourceFile:1)
	at androidx.loader.content.a$a.m(SourceFile:3)
	at androidx.loader.content.a$a.b(SourceFile:3)
	at androidx.loader.content.ModernAsyncTask$b.call(SourceFile:19)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more`

**Comment by rRemix** [comment]
再麻烦试试这个版本呢
[APlayer_v1.6.3.0_nongoogle_2024-03-25 08-50.zip](https://github.com/rRemix/APlayer/files/14737500/APlayer_v1.6.3.0_nongoogle_2024-03-25.08-50.zip)

**Comment by Nachogao** [comment]
> 再麻烦试试这个版本呢
> [APlayer_v1.6.3.0_nongoogle_2024-03-25 08-50.zip](https://github.com/rRemix/APlayer/files/14737500/APlayer_v1.6.3.0_nongoogle_2024-03-25.08-50.zip)
> 

修好了，感谢
